### ISSUE TITLE
css中的([val])变量能不能做个跳过解析

### ISSUE THREAD

**Issue by iqszlong** [tencent-cdc/sfcjs#8]
css规则里面有属性的写法，但是在这里都转换成变量了。
```css
:host([shadow]){
   box-shadow: 0 5px 10px var(--shadow-color);
}
```
在这种这情况下，并不需要进行变量转换，有没有方法跳过转换？？
